import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen`}
        >
          {/* Header */}
          <header className="flex justify-end items-center p-4 gap-4 h-16 bg-white shadow-sm">
            <SignedOut>
              <SignInButton>
                <button className="bg-white border border-gray-300 text-gray-700 rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 hover:bg-gray-50 shadow-sm">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 hover:bg-[#5a36e8] shadow-sm">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>

          {/* Main Content */}
          <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center p-4">
            <SignedOut>
              <div className="bg-white rounded-xl shadow-lg p-8 w-full max-w-md text-center">
                <h1 className="text-2xl font-bold mb-2 text-gray-800">
                  Welcome to Our App
                </h1>
                <p className="text-gray-500 mb-6">
                  Please sign in or create an account to continue
                </p>
                <div className="flex gap-3 justify-center">
                  <SignInButton>
                    <button className="bg-white border border-gray-300 text-gray-700 rounded-full font-medium text-sm h-10 px-4 hover:bg-gray-50 shadow-sm">
                      Sign In
                    </button>
                  </SignInButton>
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-4 hover:bg-[#5a36e8] shadow-sm">
                      Sign Up
                    </button>
                  </SignUpButton>
                </div>
              </div>
            </SignedOut>

            <SignedIn>
              <div >
                {children}
              </div>
            </SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
